volumes:
  bestSoccerDB:

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: userroot
      POSTGRES_DB: bestSoccerDB

    ports:
      - "5432:5432"

    volumes:
      - bestSoccerDB:/var/lib/postgresql/data